# name 필드는 워크플로의 이름을 설정합니다.
name: HelloWorld

# on 필드는 워크플로를 트리거하는 이벤트를 정의합니다.
# 여기서는 'push' 이벤트가 발생할 때 워크플로가 실행됩니다.
on: [push]

# jobs 필드는 워크플로에서 실행할 작업을 정의합니다.
jobs:
  # echo 작업을 정의합니다.
  echo:
    # runs-on 필드는 이 작업이 실행될 환경을 지정합니다.
    # 여기서는 'ubuntu-latest' 환경에서 작업이 실행됩니다.
    runs-on: ubuntu-latest

    # steps 필드는 작업 내에서 수행할 단계들을 정의합니다.
    steps:
    # 단계 이름을 'hello'로 지정하고, 'echo' 명령어를 실행하여
    # "Hello, Github Actions!" 문구를 출력합니다.
    - name: hello
      run: echo "Hello, Github Actions!"
